/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.virtualeduc.tuescuelavirtual.utils;

/**
 *
 * @author Lenin
 */
public class Constantes {
        
	public static int ALUMNO_REGISTRADO_CODE=100;
	
	public static int ALUMNO_EXISTE_CODE=101;
	
	public static int ALUMNO_INACTIVADO_CODE=102;
	
	public static int ALUMNO_MODIFICADO_CODE=103;
	
	public static int CURSO_REGISTRADO_CODE=104;
	
	public static int CURSO_MODIFICADO_CODE=105;
	
	public static int CURSO_ELIMINADO_CODE=106;
	
	public static int CURSO_EXISTE_CODE=107;
	
	public static int CURSO_IMPOSIBLE_DE_ELIMINAR_CODE=108;
	
	public static int CURSO_IMPOSIBLE_DE_MODIFICAR_CODE=109;
	
	public static int ANNIO_ESCOLAR_REGISTRADO_CODE=110;
	
	public static int CURSO_SIN_INSCRITOS_CODE=111;
	
	public static int CURSO_ACTUALIZADO_CODE=112;
	
	public static int MATERIA_REGISTRADA_CODE=113;
	
	public static int MATERIA_EXISTE_CODE=114;
	
	public static int MATERIA_MODIFICADA_CODE=115;
	
	public static int MATERIA_DESACTIVADA_CODE=116;
	
	public static int ANNIO_ESCOLAR_MODIFICADO_CODE=117;
	
	public static int ANNIO_ESCOLAR_ELIMINADO_CODE=118;
	
	public static int PROFESOR_REGISTRADO_CODE=119;
	
	public static int PROFESOR_EXISTE_CODE=120;
	
	public static int PROFESOR_MODIFICADO_CODE=121;
	
	public static int CURSO_MATERIA_ASIGNADA_CODE=122;
	
	public static int CURSO_MATERIA_ELIMINADA_CODE=123;
	
	public static int CURSO_NO_ASIGNADO=124;
        
        public static int NOTAS_REGISTRADAS=125;
        
        public static int PERIODO_LAPSO_SIN_REGISTROS_DE_NOTAS=126;
        
        public static int SIN_NOTAS_DEFINITIVAS_REGISTRADAS=127;
        
        public static int CONSULTA_EXITOSA_DE_NOTAS=128;

	public static int MODIFICACION_EXITOSA_DE_NOTAS=129;

	public static int CURSO_IMPOSIBLE_DE_ELIMINAR_CODE_1=130;

	public static int CURSO_IMPOSIBLE_DE_ELIMINAR_CODE_2=131;
        
	
	
    //mensaje2    	
	public static String ALUMNO_REGISTRADO_DESC="EL ALUMNO HA SIDO REGISTRADO CORRECTAMENTE EN EL SISTEMA";
	
	//mensaje1
	public static String ALUMNO_EXISTE_DESC="EL ALUMNO CON EL NUMERO DE CEDULA INDICADO YA EXISTE EN EL SISTEMA";
	
	//mensaje5
	public static String ALUMNO_MODIFICADO_DESC="LOS DATOS DEL ALUMNO HAN SIDO MODIFICADOS CORRECTAMENTE EN EL SISTEMA";
	
	public static String ALUMNO_INACTIVADO_DESC="EL ALUMNO HA SIDO RETIRADO E INACTIVADO EN EL SISTEMA";
	
	//mensaje3
	public static String CURSO_REGISTRADO_DESC="EL CURSO HA SIDO REGISTRADO CORRECTAMENTE EN EL SISTEMA";
	
	//mensaje4
	public static String CURSO_EXISTE_DESC="EL CURSO QUE INTENTA REGISTRAR O MODIFICAR YA EXISTE EN EL SISTEMA";
	
	//mensaje6
	public static String CURSO_MODIFICADO_DESC="LOS DATOS DEL CURSO HAN SIDO MODIFICADOS CORRECTAMENTE EN EL SISTEMA";
	
	//mensaje7
	public static String CURSO_ELIMINADO_DESC="EL CURSO HA SIDO ELIMINADO DEL SISTEMA";
	
	//mensaje8
	public static String CURSO_IMPOSIBLE_DE_ELIMINAR_DESC="NO SE PUEDE ELIMINAR ESTE CURSO YA QUE POSEE ALUMNOS VINCULADOS  ";

	
	//mensaje9
	public static String CURSO_IMPOSIBLE_DE_MODIFICAR_DESC="NO SE PUEDE MODIFICAR ESTE CURSO YA QUE POSEE ALUMNOS VINCULADOS  ";
	
	//mensaje10
	public static String ANNIO_ESCOLAR_REGISTRADO_DESC="EL PERIODO ESCOLAR HA SIDO REGISTRADO CORRECTAMENTE EN EL SISTEMA Y EL ANTERIOR HA SIDO INACTIVADO";

	//mensaje11
	public static String CURSO_SIN_INSCRITOS_DESC="ESTE CURSO NO TIENE ALUMNOS INSCRITOS";
	
	//mensaje12
	public static String CURSO_ACTUALIZADO_DESC="LOS ALUMNOS HAN SIDO CORRECTAMENTE INSCRITOS EN EL CURSO";
	
	//mensaje13
	public static String MATERIA_REGSTRADA_DESC="LA MATERIA HA SIDO REGISTRADA EN EL SISTEMA";
	
	//mensaje14
	public static String MATERIA_EXISTE_DESC="LA MATERIA YA EXISTE EN EL SISTEMA";
	
	//mensaje15
	public static String MATERIA_MODIFICADA_DESC="LA MATERIA HA SIDO MODIFICADA EN EL SISTEMA";
	
	//mensaje16
	public static String MATERIA_DESACTIVADA_DESC="LA MATERIA HA SIDO DESACTIVADA EN EL SISTEMA";
	
	
	//mensaje17
	public static String ANNIO_ESCOLAR_MODIFICADO_DESC="EL PERIODO ESCOLAR HA SIDO MODIFICADO CORRECTAMENTE EN EL SISTEMA";

	//mensaje18
	public static String ANNIO_ESCOLAR_ELIMINADO_DESC="EL PERIODO ESCOLAR HA SIDO ELIMINADO DEL SISTEMA";

	//mensaje19   	
	public static String PROFESOR_REGISTRADO_DESC="EL PROFESOR HA SIDO REGISTRADO CORRECTAMENTE EN EL SISTEMA";
	
	//mensaje20
	public static String PROFESOR_EXISTE_DESC="EL PROFESOR CON EL NUMERO DE CEDULA INDICADO YA EXISTE EN EL SISTEMA";

	//mensaje21
	public static String PROFESOR_MODIFICADO_DESC="LOS DATOS DEL PROFESOR HAN SIDO MODIFICADOS CORRECTAMENTE EN EL SISTEMA";

	//mensaje22
	public static String CURSO_MATERIA_ASIGNADA_DESC="EL(LOS) CURSO(S) HA(N) SIDO ASIGNADO(S) CORRECTAMENTE";

	//mensaje23
	public static String CURSO_MATERIA_ELIMINADA_DESC="EL CURSO HA SIDO ELIMINADO CORRECTAMENTE";
	
	//mensaje24
	public static String CURSO_NO_ASIGNADO_DESC="DEBE ASIGNAR UN CURSO PARA PODER REGISTRAR EL ALUMNO";

        //mensaje25
	public static String NOTAS_REGISTRADAS_DESC="LAS NOTAS HAN SIDO REGISTRADAS EXITÓSAMENTE";

        
        //mensaje26
	public static String PERIODO_LAPSO_SIN_REGISTROS_DE_NOTAS_DESC="NO EXISTEN NOTAS REGISTRADAS PARA ESTE PERIODO Y ESTE LAPSO";

        //mensaje27
        public static String SIN_NOTAS_DEFINITIVAS_REGISTRADAS_DESC="NO HAY NOTAS DEFINITIVAS REGISTRADAS PARA ESTE PERIODO ESCOLAR";

        //mensaje28
        public static String CONSULTA_EXITOSA_DE_NOTAS_DESC="LA CONSULTA DE NOTAS SE HA REALIZADO EXITOSAMENTE";


	//mensaje28
	public static String MODIFICACION_EXITOSA_DE_NOTAS_DESC="LA(S) NOTAS(S) SE HAN MODIFICADO EXITOSAMENTE";

	//mensaje29
	public static String CURSO_IMPOSIBLE_DE_ELIMINAR_DESC_1="NO SE PUEDE ELIMINAR ESTE CURSO YA QUE POSEE DOCENTES VINCULADOS  ";

	//mensaje30
	public static String CURSO_IMPOSIBLE_DE_ELIMINAR_DESC_2="NO SE PUEDE ELIMINAR ESTE CURSO YA QUE POSEE NOTAS VINCULADAS  ";



}
