/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.virtualeduc.tuescuelavirtual.utils;

/**
 *
 * @author Lenin
 */
public class Constantes {
        
	public static int ALUMNO_REGISTRADO_CODE=100;
	
	public static int ALUMNO_EXISTE_CODE=101;
	
	public static int ALUMNO_INACTIVADO_CODE=102;
	
	public static int ALUMNO_MODIFICADO_CODE=103;
	
	public static int CURSO_REGISTRADO_CODE=104;
	
	public static int CURSO_MODIFICADO_CODE=105;
	
	public static int CURSO_ELIMINADO_CODE=106;
	
	public static int CURSO_EXISTE_CODE=107;
	
	public static int CURSO_IMPOSIBLE_DE_ELIMINAR_CODE=108;
	
	public static int CURSO_IMPOSIBLE_DE_MODIFICAR_CODE=109;
	
	public static int ANNIO_ESCOLAR_REGISTRADO_CODE=110;
	
	public static int CURSO_SIN_INSCRITOS_CODE=111;
	
        	
	public static String ALUMNO_REGISTRADO_DESC="EL ALUMNO HA SIDO REGISTRADO CORRECTAMENTE EN EL SISTEMA";
	
	public static String ALUMNO_EXISTE_DESC="EL ALUMNO CON EL NUMERO DE CEDULA INDICADO YA EXISTE EN EL SISTEMA";
	
	public static String ALUMNO_MODIFICADO_DESC="LOS DATOS DEL ALUMNO HAN SIDO MODIFICADOS CORRECTAMENTE EN EL SISTEMA";
	
	public static String ALUMNO_INACTIVADO_DESC="EL ALUMNO HA SIDO RETIRADO E INACTIVADO EN EL SISTEMA";
	
	public static String CURSO_REGISTRADO_DESC="EL CURSO HA SIDO REGISTRADO CORRECTAMENTE EN EL SISTEMA";
	
	public static String CURSO_EXISTE_DESC="EL CURSO QUE INTENTA REGISTRAR O MODIFICAR YA EXISTE EN EL SISTEMA";
	
	public static String CURSO_MODIFICADO_DESC="LOS DATOS DEL CURSO HAN SIDO MODIFICADOS CORRECTAMENTE EN EL SISTEMA";
	
	public static String CURSO_ELIMINADO_DESC="EL CURSO HA SIDO ELIMINADO DEL SISTEMA";
	
	public static String CURSO_IMPOSIBLE_DE_ELIMINAR_DESC="NO SE PUEDE ELIMINAR ESTE CURSO YA QUE POSEE ALUMNOS VINCULADOS  ";
	
	public static String CURSO_IMPOSIBLE_DE_MODIFICAR_DESC="NO SE PUEDE MODIFICAR ESTE CURSO YA QUE POSEE ALUMNOS VINCULADOS  ";
	
	public static String ANNIO_ESCOLAR_REGISTRADO_DESC="EL PERIODO ESCOLAR HA SIDO REGISTRADO CORRECTAMENTE EN EL SISTEMA Y EL ANTERIOR HA SIDO INACTIVADO";

	public static String CURSO_SIN_INSCRITOS_DESC="ESTE CURSO NO TIENE ALUMNOS INSCRITOS";


}
